In [1]:
import numpy as np

In [5]:
# addition
var_a=np.array([1,2,3,4])
var_add= var_a+3
print(var_a)
print(var_add)

[1 2 3 4]
[4 5 6 7]


In [12]:
#add function
var_a=np.array([2,3,4,5])
var_b=np.array([5,6,7,8])
var_addf=np.add(var_a,var_b)
print(var_addf)

[ 7  9 11 13]


In [6]:
# subtract
var_a=np.array([1,2,3,4])
var_subt= var_a-1
print(var_a)
print(var_subt)

[1 2 3 4]
[0 1 2 3]


In [16]:
# subtract function
var_a=np.array([2,3,4,5])
var_b=np.array([5,6,7,8])
var_subf=np.subtract(var_a,var_b)
print(var_subf)

[-3 -3 -3 -3]


In [7]:
# multiply
var_a=np.array([2,3,4,5])
var_mul= var_a*2
print(var_a)
print(var_mul)

[2 3 4 5]
[ 4  6  8 10]


In [17]:
# multiply function
var_a=np.array([2,3,4,5])
var_b=np.array([5,6,7,8])
var_mulf=np.multiply(var_a,var_b)
print(var_mulf)

[10 18 28 40]


In [8]:
# divide
var_a=np.array([2,3,4,5])
var_div= var_a/2
print(var_a)
print(var_div)

[2 3 4 5]
[1.  1.5 2.  2.5]


In [18]:
# divide function
var_a=np.array([2,3,4,5])
var_b=np.array([5,6,7,8])
var_divf=np.divide(var_a,var_b)
print(var_divf)

[0.4        0.5        0.57142857 0.625     ]


In [10]:
# modulus
var_a=np.array([2,3,4,5])
var_mod= var_a%2
print(var_a)
print(var_mod)

[2 3 4 5]
[0 1 0 1]


In [19]:
# mod function
var_a=np.array([2,3,4,5])
var_b=np.array([5,6,7,8])
var_modf=np.mod(var_a,var_b)
print(var_modf)

[2 3 4 5]
