In [1]:
import numpy as np

In [2]:
var_a=np.array([1,2,3])
var_b=np.array([[5],[6],[7]])
print(var_a.shape)
print(var_b.shape)


(3,)
(3, 1)


In [3]:
print(var_a+var_b)

[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [4]:
var_c=np.array([[1],[2]])
var_d=np.array([[1,2,3],[3,4,5]])
print(var_c.shape)
print(var_d.shape)

(2, 1)
(2, 3)


In [5]:
print(var_c+var_d)

[[2 3 4]
 [5 6 7]]
