In [1]:
import numpy as np

In [2]:
x=[10,20,30,40]

In [9]:
y=np.array(x)
print(y)
print(y.ndim)

[10 20 30 40]
1


In [10]:
#check the type of array
print(type(y))

<class 'numpy.ndarray'>


In [11]:
l=[]
for i in range(1,4):
    int_num=int(input(" enter a value: "))
    l.append(int_num)

print(np.array(l))

 enter a value: 14
 enter a value: 55
 enter a value: 66
[14 55 66]


In [16]:
array_2=np.array([[1,2,3,4],[5,6,7,8]])
print(array_2)
print(array_2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [17]:
array_3=np.array([[[1,2,3,4],[5,6,7,8],[5,7,8,9]]])
print(array_3)
print(array_3.ndim)

[[[1 2 3 4]
  [5 6 7 8]
  [5 7 8 9]]]
3
