In [2]:
import numpy as np

# indexing

In [14]:
#indexing
var=np.array([1,2,3,4])
print(var.ndim) #print the number of dimensions
print(var[2])

1
3


In [7]:
#indexing a 2-dimension array
var1=np.array([[1,2,3,4],[3,4,5,6]])
print(var1.ndim) #print the number of dimensions
print(var1[1][1])

2
4


In [13]:
#indexing a 3-dimension array
var2=np.array([[[1,2,3],[3,4,5],[1,5,8]]])
print(var2.ndim) #print the number of dimensions
print(var2[0][1])

3
[3 4 5]


# slicing


In [19]:
var_s=np.array([1,2,3,4,5,6,7,8])
print(var_s)
print(var_s[1:3]) # prints from second data to third data.

[1 2 3 4 5 6 7 8]
[2 3]


In [20]:
print(var_s[1:]) # prints from second data to the end

[2 3 4 5 6 7 8]


In [21]:
print(var_s[:6]) # prints from the start till the sixth data

[1 2 3 4 5 6]


In [22]:
print(var_s[::3]) # prints from the start till the last data jumping 3 data from the array

[1 4 7]


In [24]:
#slicing a 2-dimension array
vars1=np.array([[1,2,3,4],[5,3,4,5]])
print(vars1)
print(vars1.ndim)

[[1 2 3 4]
 [5 3 4 5]]
2


In [27]:
print(vars1[1,2:])# prints the data from the second dimension starting from the third element till the end

[4 5]


In [28]:
print(vars1[0,2:])# prints the data from the first dimension starting from the third element till the end

[3 4]
