In [1]:
import numpy as np

In [2]:
# Iterating a one-dimensional array
x=np.array([2,3,5,7,8,2,5])
print(x)

for i in x:
    print(i)

[2 3 5 7 8 2 5]
2
3
5
7
8
2
5


In [5]:
# Iterating a two-dimensional array
y=np.array([[1,2,3],[4,5,6]])
print(y)

for j in y:
    print(j)

for k in y:
    for l in k:
        print(l)


[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [6]:
# Iterating a three-dimensional array
z=np.array([[[1,2,3,4],[4,5,6,8]]])
print(z)

for i in z:
    for j in i:
        for k in j:
            print(k)


[[[1 2 3 4]
  [4 5 6 8]]]
1
2
3
4
4
5
6
8


In [8]:
# Iterating a three-dimensional array using -nditer- function
z=np.array([[[1,2,3,4],[4,5,6,8]]])
print(z)
print(z.ndim)
print()
for i in np.nditer(z):
    print(i)

[[[1 2 3 4]
  [4 5 6 8]]]
3

1
2
3
4
4
5
6
8


In [9]:
# Iterating a three-dimensional array using -ndenumerate- function
z=np.array([[[1,2,3,4],[4,5,6,8]]])
print(z)
print(z.ndim)
print()
for i,d in np.ndenumerate(z):
    print(i,d)

[[[1 2 3 4]
  [4 5 6 8]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 1, 3) 8
