In [1]:
import numpy as np

# Join

In [4]:
#join single dimension arrays
var_a=np.array([1,2,3,4])
var_b=np.array([5,6,7,8])
var_ab=np.concatenate((var_a,var_b))
print(var_ab)

[1 2 3 4 5 6 7 8]


In [6]:
#join two dimension arrays
var_a1=np.array([[1,2,3,4],[3,4,5,6]])
var_b1=np.array([[5,6,7,8],[1,2,4,5]])
var_ab1=np.concatenate((var_a1,var_b1),axis=1)
print(var_ab1)

[[1 2 3 4 5 6 7 8]
 [3 4 5 6 1 2 4 5]]


In [7]:
#join using stack function
var_a2=np.array([[1,2,3,4],[3,4,5,6]])
var_b2=np.array([[5,6,7,8],[1,2,4,5]])
var_ab2=np.stack((var_a2,var_b2),axis=1)
print(var_ab2)

[[[1 2 3 4]
  [5 6 7 8]]

 [[3 4 5 6]
  [1 2 4 5]]]


In [8]:
#join using dstack function
var_a3=np.array([[1,2,3,4],[3,4,5,6]])
var_b3=np.array([[5,6,7,8],[1,2,4,5]])
var_ab3=np.dstack((var_a3,var_b3))
print(var_ab3)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]

 [[3 1]
  [4 2]
  [5 4]
  [6 5]]]


# Split

In [9]:
#split single dimension arrays
var_s=np.array([1,2,3,4,5,6])
ar_s=np.array_split(var_s,3)
print(ar_s)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [12]:
print(type(ar_s)) # check the data type os the split arrays

<class 'list'>


In [21]:
#split two dimension arrays
var_s2=np.array([[1,2],[6,7],[7,8]])
ar_s2=np.array_split(var_s2,2)
print(ar_s2)

[array([[1, 2],
       [6, 7]]), array([[7, 8]])]


In [25]:
ar_s3=np.array_split(var_s2,2,axis=1)
print(ar_s3)

[array([[1],
       [6],
       [7]]), array([[2],
       [7],
       [8]])]
