In [1]:
import numpy as np

In [3]:
# rand
var=np.random.rand(5)
print(var)

[0.84113535 0.29611419 0.02744823 0.66475891 0.2475776 ]


In [4]:
var_a=np.random.rand(2,3)
print(var_a)

[[0.10459068 0.11957776 0.87761525]
 [0.11413918 0.52188251 0.80952853]]


In [5]:
#randn function
var_b=np.random.randn(5)
print(var_b)

[ 0.27490868 -0.72423069  2.012701    0.24732465 -1.63683601]


In [6]:
var_b1=np.random.randn(5,3)
print(var_b1)

[[ 1.32870979 -0.49425795 -0.32265267]
 [-1.16085287  1.52878679 -0.16998109]
 [-1.53408197 -0.20948447  0.3762637 ]
 [ 0.79297701 -1.39780215  1.37836368]
 [-0.42889814  0.64280206 -1.66281957]]


In [8]:
#ranf
var_c=np.random.ranf(5)
print(var_c)

[0.89987903 0.82050909 0.74945146 0.54928635 0.1418526 ]


In [11]:
#randint
var_d=np.random.randint(10,100,4)
print(var_d)

[46 80 94 64]
