In [2]:
import numpy as np

In [5]:
var_a=np.array([[1,2],[3,4]])
print(var_a)
print("The shape is " ,var_a.shape)

[[1 2]
 [3 4]]
The shape is  (2, 2)


In [7]:
var_a2=np.array([[1,2,4],[3,4,6]])
print(var_a2)
print("The shape is " ,var_a2.shape)

[[1 2 4]
 [3 4 6]]
The shape is  (2, 3)


In [15]:
#reshape array
var_a3=np.array([1,2,3,4,5,6])
x=var_a3.reshape(3,2)
print(var_a3)
print()
print(x)
print(x.ndim)

[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]
2
