In [1]:
import numpy as np

In [2]:
# one-dimensional zero array
ar_zero=np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [5]:
# two-dimensional zero array
ar2_zero=np.zeros((2,4))
print(ar2_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# two-dimensional ones array
ar1_one=np.ones((2,4))
print(ar1_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# empty array
ar1_empty=np.empty(4)
print(ar1_empty)

[0. 0. 0. 0.]


In [8]:
#range array
ar_rn=np.arange(4)
print(ar_rn)

[0 1 2 3]


In [11]:
#diagnal array
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
ar_dia2=np.eye(3,5)
print(ar_dia2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [17]:
#line-space function
ar_lin=np.linspace(0,30,num=10)
print(ar_lin)

[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.         23.33333333 26.66666667 30.        ]
